### PR TITLE
fix network metric value for multiple interfaces

### LINKED ISSUE #1058: Network usage for physical servers doesn't appear in grafana
Hello, 

When installing k8s, with heapster and inluxdb, network utilization appears in grafana for my VMs but not for my physical servers. 

I'm using: v0.20.0-alpha12, heapster_influxdb:v0.5, heapster_grafana:v2.6.0-2. 

My guess is that the network interfaces on the phsyical machines aren't being picked up correctly, but I'm not sure. My physical machines using a bond0 sub interface (bond0.3691, which the stats may or may not also appear in bond0 main interface) and my VMs use a eth0 interface.

My network interfaces on ubuntu VMs are (which show up in grafana):
CA2KLE1V04K8N01 | SUCCESS | rc=0 >>
docker0   Link encap:Ethernet  HWaddr 02:42:e8:5e:ed:e1  
          inet addr:10.244.38.1  Bcast:0.0.0.0  Mask:255.255.255.0
          inet6 addr: fe80::42:e8ff:fe5e:ede1/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1450  Metric:1
          RX packets:57043 errors:0 dropped:0 overruns:0 frame:0
          TX packets:60978 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:11149744 (11.1 MB)  TX bytes:95075935 (95.0 MB)

eth0      Link encap:Ethernet  HWaddr 00:0c:29:0a:59:b6  
          inet addr:10.56.184.127  Bcast:10.56.184.255  Mask:255.255.255.0
          inet6 addr: fe80::20c:29ff:fe0a:59b6/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:443263 errors:0 dropped:48 overruns:0 frame:0
          TX packets:124476 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:588347772 (588.3 MB)  TX bytes:20500781 (20.5 MB)

flannel.1 Link encap:Ethernet  HWaddr 0a:ea:96:4f:a9:05  
          inet addr:10.244.38.0  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::8ea:96ff:fe4f:a905/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1450  Metric:1
          RX packets:48009 errors:0 dropped:0 overruns:0 frame:0
          TX packets:47230 errors:0 dropped:8 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:2622062 (2.6 MB)  TX bytes:11866415 (11.8 MB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

veth7538099 Link encap:Ethernet  HWaddr 62:60:47:2d:55:c7  
          inet6 addr: fe80::6060:47ff:fe2d:55c7/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1450  Metric:1
          RX packets:3 errors:0 dropped:0 overruns:0 frame:0
          TX packets:54 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:258 (258.0 B)  TX bytes:4468 (4.4 KB)

veth32c0372 Link encap:Ethernet  HWaddr ba:4b:2c:a8:9d:82  
          inet6 addr: fe80::b84b:2cff:fea8:9d82/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1450  Metric:1
          RX packets:3 errors:0 dropped:0 overruns:0 frame:0
          TX packets:38 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:258 (258.0 B)  TX bytes:3112 (3.1 KB)

veth4b5358c Link encap:Ethernet  HWaddr 2e:04:9d:ef:c8:6e  
          inet6 addr: fe80::2c04:9dff:feef:c86e/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1450  Metric:1
          RX packets:3 errors:0 dropped:0 overruns:0 frame:0
          TX packets:42 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:258 (258.0 B)  TX bytes:3448 (3.4 KB)

veth833397e Link encap:Ethernet  HWaddr 56:11:f0:fe:ed:d6  
          inet6 addr: fe80::5411:f0ff:fefe:edd6/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1450  Metric:1
          RX packets:3 errors:0 dropped:0 overruns:0 frame:0
          TX packets:69 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:258 (258.0 B)  TX bytes:5774 (5.7 KB)

veth99b1b48 Link encap:Ethernet  HWaddr c2:6c:f2:d0:cb:14  
          inet6 addr: fe80::c06c:f2ff:fed0:cb14/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1450  Metric:1
          RX packets:7234 errors:0 dropped:0 overruns:0 frame:0
          TX packets:10647 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:8496046 (8.4 MB)  TX bytes:90437036 (90.4 MB)

vethc9ec562 Link encap:Ethernet  HWaddr 8a:f4:2e:42:09:43  
          inet6 addr: fe80::88f4:2eff:fe42:943/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1450  Metric:1
          RX packets:45548 errors:0 dropped:0 overruns:0 frame:0
          TX packets:45421 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:3081348 (3.0 MB)  TX bytes:3102558 (3.1 MB)

vethebdbecc Link encap:Ethernet  HWaddr ba:7a:b2:23:ea:13  
          inet6 addr: fe80::b87a:b2ff:fe23:ea13/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1450  Metric:1
          RX packets:3 errors:0 dropped:0 overruns:0 frame:0
          TX packets:93 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:258 (258.0 B)  TX bytes:7830 (7.8 KB)

vethecf29c7 Link encap:Ethernet  HWaddr 8e:70:c1:10:ed:42  
          inet6 addr: fe80::8c70:c1ff:fe10:ed42/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1450  Metric:1
          RX packets:4174 errors:0 dropped:0 overruns:0 frame:0
          TX packets:5245 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:364595 (364.5 KB)  TX bytes:1565476 (1.5 MB)

My network interfaces on physical servers running ubuntu (that do not appear) are:
VA1KLE1V04K8N01 | SUCCESS | rc=0 >>
bond0     Link encap:Ethernet  HWaddr 5c:b9:01:89:7f:18  
          inet6 addr: fe80::5eb9:1ff:fe89:7f18/64 Scope:Link
          UP BROADCAST RUNNING MASTER MULTICAST  MTU:1500  Metric:1
          RX packets:548734 errors:0 dropped:0 overruns:0 frame:0
          TX packets:153974 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:745840709 (745.8 MB)  TX bytes:81823807 (81.8 MB)

bond0.3691 Link encap:Ethernet  HWaddr 5c:b9:01:89:7f:18  
          inet addr:10.136.191.14  Bcast:10.136.191.255  Mask:255.255.255.0
          inet6 addr: fe80::5eb9:1ff:fe89:7f18/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:138271 errors:0 dropped:0 overruns:0 frame:0
          TX packets:109654 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:718142603 (718.1 MB)  TX bytes:78895997 (78.8 MB)

docker0   Link encap:Ethernet  HWaddr 02:42:57:91:fe:1f  
          inet addr:10.244.41.1  Bcast:0.0.0.0  Mask:255.255.255.0
          inet6 addr: fe80::42:57ff:fe91:fe1f/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1450  Metric:1
          RX packets:57688 errors:0 dropped:0 overruns:0 frame:0
          TX packets:68517 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:6178145 (6.1 MB)  TX bytes:33237405 (33.2 MB)

eth0      Link encap:Ethernet  HWaddr 5c:b9:01:89:7f:18  
          UP BROADCAST RUNNING SLAVE MULTICAST  MTU:1500  Metric:1
          RX packets:548734 errors:0 dropped:0 overruns:0 frame:0
          TX packets:153974 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:745840709 (745.8 MB)  TX bytes:81823807 (81.8 MB)

eth1      Link encap:Ethernet  HWaddr 5c:b9:01:89:7f:19  
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

flannel.1 Link encap:Ethernet  HWaddr da:18:70:7a:3b:5c  
          inet addr:10.244.41.0  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::d818:70ff:fe7a:3b5c/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1450  Metric:1
          RX packets:62698 errors:0 dropped:0 overruns:0 frame:0
          TX packets:52517 errors:0 dropped:8 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:30007304 (30.0 MB)  TX bytes:6896825 (6.8 MB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:2 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:176 (176.0 B)  TX bytes:176 (176.0 B)

veth0245420 Link encap:Ethernet  HWaddr 4e:f3:99:57:c4:41  
          inet6 addr: fe80::4cf3:99ff:fe57:c441/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1450  Metric:1
          RX packets:3 errors:0 dropped:0 overruns:0 frame:0
          TX packets:221 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:258 (258.0 B)  TX bytes:18706 (18.7 KB)

veth6431319 Link encap:Ethernet  HWaddr b6:a2:54:e4:98:5d  
          inet6 addr: fe80::b4a2:54ff:fee4:985d/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1450  Metric:1
          RX packets:3 errors:0 dropped:0 overruns:0 frame:0
          TX packets:330 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:258 (258.0 B)  TX bytes:28056 (28.0 KB)

veth6828898 Link encap:Ethernet  HWaddr 1e:e3:2d:c5:0b:12  
          inet6 addr: fe80::1ce3:2dff:fec5:b12/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1450  Metric:1
          RX packets:3 errors:0 dropped:0 overruns:0 frame:0
          TX packets:98 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:258 (258.0 B)  TX bytes:8200 (8.2 KB)

veth9697223 Link encap:Ethernet  HWaddr 7e:74:a7:be:6d:ed  
          inet6 addr: fe80::7c74:a7ff:febe:6ded/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1450  Metric:1
          RX packets:8 errors:0 dropped:0 overruns:0 frame:0
          TX packets:48 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:648 (648.0 B)  TX bytes:3952 (3.9 KB)

veth9820230 Link encap:Ethernet  HWaddr 5a:fe:87:79:6d:02  
          inet6 addr: fe80::58fe:87ff:fe79:6d02/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1450  Metric:1
          RX packets:3 errors:0 dropped:0 overruns:0 frame:0
          TX packets:283 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:258 (258.0 B)  TX bytes:24018 (24.0 KB)

veth023b0fe Link encap:Ethernet  HWaddr 9e:47:72:d7:b1:02  
          inet6 addr: fe80::9c47:72ff:fed7:b102/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1450  Metric:1
          RX packets:3 errors:0 dropped:0 overruns:0 frame:0
          TX packets:203 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:258 (258.0 B)  TX bytes:17166 (17.1 KB)

### PR DESCRIPTION
**Pull request by andyxning**
Fix #1058 

This PR will fix the network metric values when there are multiple interface available for a container. Currently, heapster will use the first one(index 0) interface stats as the value for network metrics. This will be wrong when there are more than one network interface available for a container.

What we should do is to summarize all the network interface values instead of only picking up only one.

/cc @DirectXMan12 @piosz @ckleban @CBR09 @xiangpengzhao

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
Besides this PR does, we may also want to collect and show the metrics of every network interfaces, right? i.e., the metrics can be shown in the array `interfaces` in the example of https://github.com/google/cadvisor/issues/1593

**Comment by andyxning** [comment]
@xiangpengzhao IIUC, you mean that we should add a network interface label to network interface metrics?

It it is true, I suggest we postpone it as it will break the backward compatibility.

**Comment by xiangpengzhao** [comment]
@andyxning correct. agreed  :)

**Review by DirectXMan12 — CHANGES_REQUESTED** [review]
IIRC, GetValue only applies for the non-summary source, which is deprecated.  We should fix this in the summary source as well.

**Comment by andyxning** [comment]
> GetValue only applies for the non-summary source, which is deprecated.

@DirectXMan12 you mean that none-summary source has been deprecated? or summary source is deprecated? I am sorry i am not getting it.

After a looking at the summary source response, i have not found any info corresponding to different interface values from it. summary source response only contains one [`NetworkStats`](https://github.com/kubernetes/heapster/blob/master/vendor/k8s.io/kubernetes/pkg/kubelet/api/v1alpha1/stats/types.go#L126-L141). I think we should first fix this in kubelet.

As for now, kubernetes 1.8 has been code freezed, it may not be added to 1.8. I will give it a try. But for now, we need this fix for normal kuberbnetes source. So would it ok for you to merge this PR first. :) I will open an issue for summary source to keep it tracked.

**Comment by andyxning** [comment]
@DirectXMan12 After looking into [Kubernetes #22542](https://github.com/kubernetes/kubernetes/pull/22542), it turns out that heapster addon uses summary api by default.

**Comment by andyxning** [comment]
@DirectXMan12 A fix PR has been fired to [Kubernetes #52144](https://github.com/kubernetes/kubernetes/pull/52144)

**Comment by andyxning** [comment]
/ping @DirectXMan12 @piosz PTAL. Can this PR be merged?

**Comment by andyxning** [comment]
@DirectXMan12 @piosz I have updated the PR in [kubernetes #52144](https://github.com/kubernetes/kubernetes/pull/52144). PTAL.

**Comment by bartebor** [comment]
Summarizing network interfaces' stats can (will) give wrong results for given node when machine uses bonding for enhancing bandwith or link reliability.
For example our kubernetes nodes have two physical intefraces `eno1` and `eno2` bonded into `bond0`.
In that case we will double stats since `bond0` and its physical interfaces essentially share the same statistics.
I think we should have possibility to manually pick network interface(s) to summarize on given node. It probably should be done in kubelet, since interface names may vary from node to node. Heapster could use values from `/stats/summary`, but it is broken at the moment (searches for `eth0`) or `/stats/`, which is broken too (takes first interface from the list).

I am not sure if this applies also to container stats; I think there is no case in kubernetes where such complicated newtork setup is created.

**Comment by andyxning** [comment]
@bartebor The network settings will be complicated to be coherent to all different possible network setup. For now, we should make the atomic data as detail as possible and let the upper application, like heapster, to query and make the decision about how to aggregate the original data.

**Comment by bartebor** [comment]
@andyxning I agree that we should have and provide detailed network info. Heapster of course can make decision how to treat such data. The problem is nodes are different and cannot be treated in the same way.
That's why I suggested to have this done in kubelet, because we could set those policies locally while node provisioning and do not make clients aware of such peculiarities ;) 

Otherwise we should teach heapster to differentiate nodes somehow and apply specific algorithm in each case. Given that nodes come and go somewhat frequently this should be done in some general way (node labels?) to eliminate need of, say, heapster restart.

Discussion of the latter should happen in heapster issue of course.

**Comment by andyxning** [comment]
@DirectXMan12 The PR in kubernetes to change summary api has been merged. Could you please take a look at this.

**Comment by andyxning** [comment]
@kubernetes/heapster-maintainers PTAL.

File: metrics/core/metrics.go [hunk 1]
```diff
@@ -343,10 +348,15 @@ var MetricNetworkRxErrors = Metric{
 		return spec.HasNetwork
 	},
 	GetValue: func(spec *cadvisor.ContainerSpec, stat *cadvisor.ContainerStats) MetricValue {
+		var rxErrors int64 = 0
```
Comment (loburm) [inline metrics/core/metrics.go]: what about:
rxErrors := uint64(0)

File: metrics/core/metrics.go [hunk 2]
```diff
@@ -343,10 +348,15 @@ var MetricNetworkRxErrors = Metric{
...
+		for _, interfaceStat := range stat.Network.Interfaces {
+			rxErrors += int64(interfaceStat.RxErrors)
```
Comment (loburm) [inline metrics/core/metrics.go]: let's make only one conversion below:
IntValue: int64(rxErrors)

**Review by loburm — CHANGES_REQUESTED** [review]

**Comment by DirectXMan12** [comment]
Sorry it took me so long to get back to this.  Shouldn't we just make network a labeled metric now, instead of aggregating like this, since we now have per-interface stats?  People can aggregate together in their sink.

File: metrics/core/metrics.go (hunk 2 above)
Comment (andyxning) [reply metrics/core/metrics.go]: Will do.

**Comment by andyxning** [comment]
> Shouldn't we just make network a labeled metric now, instead of aggregating like this, since we now have per-interface stats? People can aggregate together in their sink.

@DirectXMan12 IMO, make network a labeled metric is not a backward compatible change. I'd like to postpone making this change. For this PR i suggest we only fix the network metrics values. I agree that for a long run, we need to split the network metrics according to different interfaces. This need another PR, however.

**Comment by andyxning** [comment]
Ping @DirectXMan12 @piosz

**Comment by andyxning** [comment]
Thanks @piosz @DirectXMan12
