### PR TITLE
Skip TestEventsBasic broken and flaky test

### LINKED ISSUE #537: Kube_events_test is flaky
```
ok  	k8s.io/heapster/sinks/influxdb	0.021s
E0911 10:19:27.005150    3197 iowatcher.go:108] Unable to decode an event from the watch stream: got invalid watch event type: 
--- FAIL: TestEventsBasic-2 (0.01s)
	Location:	kube_events_test.go:43
	Error:		No error is expected but got Error: received an event list with nil Items.
		
FAIL
FAIL	k8s.io/heapster/sources	0.072s
```

### LINKED ISSUE #565: sources/kube_events_test is flaky
```
ok  	k8s.io/heapster/sinks/influxdb	0.024s
E0916 20:33:55.119343    3264 iowatcher.go:108] Unable to decode an event from the watch stream: got invalid watch event type: 
E0916 20:33:55.120989    3264 iowatcher.go:108] Unable to decode an event from the watch stream: got invalid watch event type: 
--- FAIL: TestEventsBasic-2 (0.01s)
	Location:	kube_events_test.go:43
	Error:		No error is expected but got Events watchLoop failed with error: watchLoop channel closed
		
E0916 20:33:55.138543    3264 reflector.go:136] Failed to list *api.Pod: Get http://127.0.0.1:36459/api/v1/pods?fieldSelector=spec.nodeName%21%3D: dial tcp 127.0.0.1:36459: connection refused
E0916 20:33:55.139808    3264 reflector.go:136] Failed to list *api.Namespace: Get http://127.0.0.1:55738/api/v1/namespaces: dial tcp 127.0.0.1:55738: connection refused
FAIL
FAIL	k8s.io/heapster/sources	0.081s
```

### PR DESCRIPTION
**Pull request by mvdan**
As discussed offline with @vishh, this test is fundamentally broken and
doesn't test anything properly. It doesn't fail because the events list never
gets processed. If it does, #537 takes place since the events list is wrong.
Even if it doesn't, #565 can also appear.

Since the test is flawed and flaky, best remove it until it is rewritten
properly. Right now it's causing issues with pull requests since its flakyness
comes up often thanks to -race.

### CODE REVIEW

File: sources/kube_events_test.go [hunk 1]
```diff
@@ -13,33 +13,3 @@
 // limitations under the License.
```
Comment (vishh) [inline sources/kube_events_test.go]: Why retain this file?

**Comment by vishh** [comment]
LGTM
