### PR TITLE
fixing elasticsearch and adding tests

### LINKED ISSUE #1211: Elasticsearch sink not working
I have setup an elk stack in its own namespace, aka `es`. And there is a service called: `elasticsearch.es.svc.cluster.local`.

For the sink option I simply use: `--sink=elasticsearch:http://elasticsearch.es.svc.cluster.local:9200". This does not work and i suppose it has to do with: 

```
    // Set the URL endpoints of the ES's nodes. Notice that when sniffing is
    // enabled, these URLs are used to initially sniff the cluster on startup.
    if len(opts["nodes"]) < 1 {
        return nil, fmt.Errorf("There is no node assigned for connecting ES cluster")
    }
```

In case I and the `?nodes...` param, then I get:

```
factory.go:74] Failed to create sink: failed to create ElasticSearch client: no Elasticsearch node available
```

I have also tried to play with the sniff, timeouts etc options, so I'm stuck for the time being and the elasticsearch sink does not work

(Question: the nodes paramater seems to be mandatory? According to the `if len(opts["nodes"]) < 1`? Why is that?)

### PR DESCRIPTION
**Pull request by astropuffin**
fixes [1211](https://github.com/kubernetes/heapster/issues/1211) and adds a test so it doesn't happen again.

Root cause:
Opaque would work if it was set, but uri.Parse does not actually set Opaque.

### CODE REVIEW

**Comment by astropuffin** [comment]
Linux Foundation LCA is stuck in limbo for tech reasons. Can I get someone to review this in the meantime?

**Comment by astropuffin** [comment]
@DirectXMan12 this should be sink/elasticsearch, not influxdb.

**Comment by andyxning** [comment]
Will Review this later.

=======
Andy Xie


2017-02-16 4:24 GMT+08:00 Joseph Schneider <notifications@github.com>:

**Comment by DirectXMan12** [comment]
> this should be sink/elasticsearch, not influxdb.

so it should, I think I was triaging too fast :-P

File: common/elasticsearch/elasticsearch_test.go [hunk 1]
```diff
@@ -96,3 +96,56 @@ func TestCreateElasticSearchServiceForDefaultClusterName(t *testing.T) {
...
+
+	actualClientRefl := reflect.ValueOf(esSvc.EsClient).Elem()
+	expectedClientRefl := reflect.ValueOf(expectedClient).Elem()
+
+	if actualClientRefl.FieldByName("basicAuthUsername").String() != expectedClientRefl.FieldByName("basicAuthUsername").String() {
+		t.Fatal("basicAuthUsername is not equal")
+	}
+	if actualClientRefl.FieldByName("basicAuthUsername").String() != expectedClientRefl.FieldByName("basicAuthUsername").String() {
+		t.Fatal("basicAuthUsername is not equal")
+	}
```
Comment (andyxning) [inline common/elasticsearch/elasticsearch_test.go]: The above check for `basicAuthUsername` duplicates.

File: common/elasticsearch/elasticsearch.go [hunk 2]
```diff
@@ -127,8 +127,8 @@ func CreateElasticSearchService(uri *url.URL) (*ElasticSearchService, error) {
 	var startupFns []elastic.ClientOptionFunc
 	if len(opts["nodes"]) > 0 {
 		startupFns = append(startupFns, elastic.SetURL(opts["nodes"]...))
-	} else if uri.Opaque != "" {
-		startupFns = append(startupFns, elastic.SetURL(uri.Opaque))
+	} else if uri.Scheme != "" && uri.Host != "" {
```
Comment (andyxning) [inline common/elasticsearch/elasticsearch.go]: SGTM.

BTW, i think we need to document this behavior in the elasticsearch sink document.

**Comment by andyxning** [comment]
@astropuffin Seems you have not successfully signing linux foundation cla yet. You need to do that first. :)

**Comment by andyxning** [comment]
@astropuffin 

We need add more info for the root cause. This is useful for us to firstly get what this PR will do and why the original code can not satisfy our goal. :) 

> Root cause:
Opaque would work if it was set, but uri.Parse does not actually set Opaque.

According to [golang url doc](https://golang.org/pkg/net/url/#URL), Opaque will only be setted when uri is in the format like below:
> scheme:opaque[?query][#fragment]

**Comment by AlmogBaku** [comment]
Sgtm. OP please address @andyxning notes

**Comment by astropuffin** [comment]
hey. still working with my VP on the linux foundation signing. Jumping back in on this.

**Comment by astropuffin** [comment]
@andreykurilin re: comment
empirically, when I set the config like so: `--sink=elasticsearch:http://elasticsearch.example.com:9200?esUserName=$ES_USER&esUserSecret=$ES_PASS&sniff=false&maxRetries=1` then the opaque is not set. I was able to confirm this is the behavior of `net/url`'s parse method.

not fully following what the question/action item is here. I hope that addressed it?

**Comment by andyxning** [comment]
@astropuffin Yes, you're right. This PR will solve your empirical usage. :) 

The last step you need is to resolve your linuxfoundation CLA. :)

**Comment by AlmogBaku** [comment]
@astropuffin can your please sign the cla?

**Comment by DirectXMan12** [comment]
@piosz this should merge before 1.3.

**Comment by astropuffin** [comment]
Hey, trying to get the CLA signed. Honestly, I have no idea what the problem is with the signing process. It seems to be stuck in limbo even though we've signed it.

**Comment by astropuffin** [comment]
ok there. finally figured it out. :/

**Comment by andyxning** [comment]
@astropuffin Overall LGTM. Just two nits
* could you please squeeze you commits with `git rebase`. :)
* IMO, we need to document this usage when just using one es backend.

**Comment by astropuffin** [comment]
Ah, I assumed that it would be squashed on merge. I'll add a few lines of documentation and rebase. :)

**Comment by piosz** [comment]
@astropuffin ETA? I want to cut release ASAP and this is the only PR I'm waiting for.

**Comment by astropuffin** [comment]
ETA 30min

**Comment by piosz** [comment]
@k8s-bot ok to test

**Comment by astropuffin** [comment]
rebased and with docs

**Comment by piosz** [comment]
Thanks!
